#############################
# Xiaomi Mi Air Purifier 2H #
#     del Soggiorno         #
#                           #
# credits:                  #
# automations by @MickL     #
#                           #
# 'pm25 above 70' automation#
# created by me             #
#                           #
#############################
- id: purifier_mode_change
  alias: Air Purifier (mode change)
  trigger:
  - entity_id: input_select.xiaomi_airpurifier_mode
    platform: state
  action:
  - data_template:
      entity_id: fan.xiaomi_miio_device
      speed: '{{ states.input_select.xiaomi_airpurifier_mode.state }}'
    service: fan.set_speed
- id: purifier_mode_changed
  alias: Air Purifier (mode changed)
  trigger:
  - entity_id: fan.xiaomi_miio_device
    platform: state
  action:
  - data_template:
      option: '{{ states.fan.xiaomi_miio_device.attributes.speed }}'
    entity_id: input_select.xiaomi_airpurifier_mode
    service: input_select.select_option
- id: purifier_fav_level_change
  alias: Air Purifier (favorite level change)
  trigger:
  - entity_id: input_number.xiaomi_airpurifier_favorite_level
    platform: state
  action:
  - data_template:
      entity_id: fan.xiaomi_miio_device
      level: '{{ states.input_number.xiaomi_airpurifier_favorite_level.state | int
        }}'
    service: xiaomi_miio.fan_set_favorite_level
- id: purifier_fav_level_changed
  alias: Air Purifier (favorite level changed)
  trigger:
  - entity_id: fan.xiaomi_miio_device
    platform: state
  action:
  - data_template:
      value: '{{ states.fan.xiaomi_miio_device.attributes.favorite_level }}'
    entity_id: input_number.xiaomi_airpurifier_favorite_level
    service: input_number.set_value
#################
# pm25 above 70 #
#################
- id: '1585256200784'
  alias: Air Purifier - Migliora la qualità dell'aria
  description: il valore pm25 supera i 70
  trigger:
  - above: '70'
    entity_id: sensor.xiaomi_airpurifier_air_quality_pm25
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Ho acceso il purificatore per areare il soggiorno
    service: notify.telegram
  - data: {}
    entity_id: fan.xiaomi_miio_device
    service: fan.turn_on
