#############################
# Xiaomi Mi Air Purifier 2H #
#     del Soggiorno         #
#                           #
# credits:                  #
# sensors, switches &       #
# inputs by @MickL          #
#                           #
# 'filter hours used' sensor#
# created by me             #
#                           #
#############################
fan:
- platform: xiaomi_miio
  host: 192.168.178.34
  token: !secret air_purifier_2h_token
  name: "Xiaomi Air Purifier 2H"
#  model: zhimi.airpurifier.mc2
#
sensor:
  # Xiaomi Air Purifier 2H
  - platform: template
    sensors:
      xiaomi_airpurifier_temp:
        friendly_name: "Temperature"
        value_template: "{{ state_attr('fan.xiaomi_miio_device', 'temperature') }}"
        unit_of_measurement: "°C"
        device_class: "temperature"
      xiaomi_airpurifier_humidity:
        friendly_name: "Humidity"
        value_template: "{{ state_attr('fan.xiaomi_miio_device', 'humidity') }}"
        unit_of_measurement: "%"
        device_class: "humidity"
      xiaomi_airpurifier_air_quality_pm25:
        friendly_name: "Air quality"
        value_template: "{{ state_attr('fan.xiaomi_miio_device', 'aqi') }}"
        unit_of_measurement: "μg/m³"
        icon_template: "mdi:weather-fog"
      xiaomi_airpurifier_speed:
        friendly_name: "Fan speed"
        value_template: "{{ state_attr('fan.xiaomi_miio_device', 'motor_speed') }}"
        unit_of_measurement: "rpm"
        icon_template: "mdi:speedometer"
      xiaomi_airpurifier_filter_remaining:
        friendly_name: "Filter remaining"
        value_template: "{{ state_attr('fan.xiaomi_miio_device', 'filter_life_remaining') }}"
        unit_of_measurement: "%"
        icon_template: "mdi:heart-outline"
      xiaomi_airpurifier_filter_hours_used:
        friendly_name: "Hours Used"
        unit_of_measurement: 'h'
        value_template: "{{ state_attr('fan.xiaomi_miio_device', 'filter_hours_used') }}"
#
switch:
  # Xiaomi Air Purifier 2H
  - platform: template
    switches:
      xiaomi_airpurifier_led:
        friendly_name: "LED"
        value_template: "{{ is_state_attr('fan.xiaomi_miio_device', 'led', true) }}"
        turn_on:
          service: xiaomi_miio.fan_set_led_on
          data:
            entity_id: fan.xiaomi_miio_device
        turn_off:
          service: xiaomi_miio.fan_set_led_off
          data:
            entity_id: fan.xiaomi_miio_device
        icon_template: "mdi:lightbulb-outline"
      xiaomi_airpurifier_child_lock:
        friendly_name: "Child lock"
        value_template: "{{ is_state_attr('fan.xiaomi_miio_device', 'child_lock', true) }}"
        turn_on:
          service: xiaomi_miio.fan_set_child_lock_on
          data:
            entity_id: fan.xiaomi_miio_device
        turn_off:
          service: xiaomi_miio.fan_set_child_lock_off
          data:
            entity_id: fan.xiaomi_miio_device
        icon_template: "mdi:lock-outline"
      xiaomi_airpurifier_buzzer:
        friendly_name: "Buzzer"
        value_template: "{{ is_state_attr('fan.xiaomi_miio_device', 'buzzer', true) }}"
        turn_on:
          service: xiaomi_miio.fan_set_buzzer_on
          data:
            entity_id: fan.xiaomi_miio_device
        turn_off:
          service: xiaomi_miio.fan_set_buzzer_off
          data:
            entity_id: fan.xiaomi_miio_device
        icon_template: "mdi:volume-high"
#  
input_select:
  # Xiaomi Air Purifier 2H
  xiaomi_airpurifier_mode:
    name: Mode
    options:
      - Auto
      - Silent
      - Favorite
#      - Idle
    icon: "mdi:animation-outline"
#
input_number:
  # Xiaomi Air Purifier 2H
  xiaomi_airpurifier_favorite_level:
    name: "Favorite level"
    initial: 0
    min: 0
    max: 14
    step: 1
    icon: "mdi:weather-windy"
#
#############################
# Xiaomi Mi Air Purifier 2H #
#     (automations)        #
#                           #
# credits:                  #
# automations by @MickL     #
#                           #
# 'pm25 above 70' automation#
# created by me             #
#                           #
#############################
#
automation:
- id: '1585256200784'
  alias: Air Purifier - Migliora la qualità dell'aria
  description: il valore pm25 supera i 70
  trigger:
  - above: '70'
    entity_id: sensor.xiaomi_airpurifier_air_quality_pm25
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Ho acceso il purificatore per areare il soggiorno
    service: notify.telegram
  - data: {}
    entity_id: fan.xiaomi_miio_device
    service: fan.turn_on
#
- id: purifier_mode_change
  alias: Air Purifier (mode change)
  trigger:
  - entity_id: input_select.xiaomi_airpurifier_mode
    platform: state
  action:
  - data_template:
      entity_id: fan.xiaomi_miio_device
      speed: '{{ states.input_select.xiaomi_airpurifier_mode.state }}'
    service: fan.set_speed
- id: purifier_mode_changed
  alias: Air Purifier (mode changed)
  trigger:
  - entity_id: fan.xiaomi_miio_device
    platform: state
  action:
  - data_template:
      option: '{{ states.fan.xiaomi_miio_device.attributes.speed }}'
    entity_id: input_select.xiaomi_airpurifier_mode
    service: input_select.select_option
- id: purifier_fav_level_change
  alias: Air Purifier (favorite level change)
  trigger:
  - entity_id: input_number.xiaomi_airpurifier_favorite_level
    platform: state
  action:
  - data_template:
      entity_id: fan.xiaomi_miio_device
      level: '{{ states.input_number.xiaomi_airpurifier_favorite_level.state | int
        }}'
    service: xiaomi_miio.fan_set_favorite_level
- id: purifier_fav_level_changed
  alias: Air Purifier (favorite level changed)
  trigger:
  - entity_id: fan.xiaomi_miio_device
    platform: state
  action:
  - data_template:
      value: '{{ states.fan.xiaomi_miio_device.attributes.favorite_level }}'
    entity_id: input_number.xiaomi_airpurifier_favorite_level
    service: input_number.set_value
